name: flutter_dart_drift_sample
description: "flutter dart drift package sample"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  drift: ^2.19.1+1
  sqlite3_flutter_libs: ^0.5.27
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  drift_dev: ^2.19.1
  build_runner: ^2.4.9


flutter:


  uses-material-design: true


